/**
 * @license Copyright (c) 2003-2024, CKSource Holding sp. z o.o. All rights reserved.
 * CKEditor 4 LTS ("Long Term Support") is available under the terms of the Extended Support Model.
 */

/* exported CKBUILDER_CONFIG */

var CKBUILDER_CONFIG = {
	skin: 'moono',
	ignore: [
		'bender.js',
		'bender.ci.js',
		'bender-runner.config.json',
		'.bender',
		'bender-err.log',
		'bender-out.log',
		'.circleci',
		'dev',
		'docs',
		'.DS_Store',
		'.editorconfig',
		'.gitignore',
		'.gitattributes',
		'.github',
		'gruntfile.js',
		'.idea',
		'.jscsrc',
		'.jshintignore',
		'.jshintrc',
		'less',
		'.mailmap',
		'.nvmrc',
		'node_modules',
		'package.json',
		'README.md',
		'tests'
	],
	plugins: {
		a11yhelp: 0,
		about: 1,
		basicstyles: 1,
		bidi: 0,
		blockquote: 0,
		clipboard: 1,
		colorbutton: 0,
		colordialog: 0,
		copyformatting: 0,
		contextmenu: 0,
		dialogadvtab: 0,
		div: 0,
		elementspath: 0,
		enterkey: 1,
		entities: 1,
		filebrowser: 0,
		find: 0,
		floatingspace: 1,
		font: 0,
		format: 0,
		forms: 0,
		horizontalrule: 0,
		htmlwriter: 0,
		iframe: 0,
		image: 0,
		indentlist: 1,
		indentblock: 0,
		justify: 0,
		language: 0,
		link: 0,
		list: 1,
		liststyle: 0,
		magicline: 0,
		maximize: 0,
		newpage: 0,
		pagebreak: 0,
		pastefromlibreoffice: 0,
		pastefromword: 1,
		pastetext: 0,
		editorplaceholder: 0,
		preview: 0,
		print: 0,
		removeformat: 0,
		resize: 0,
		save: 0,
		selectall: 0,
		showblocks: 0,
		showborders: 0,
		smiley: 0,
		sourcearea: 0,
		specialchar: 0,
		stylescombo: 0,
		tab: 0,
		table: 0,
		tableselection: 0,
		tabletools: 0,
		templates: 0,
		toolbar: 1,
		undo: 1,
		uploadimage: 0,
		wysiwygarea: 1
	}
};
